### ISSUE TITLE
Are we sure we need " of " in dates?

### ISSUE THREAD

**Issue by volodymyr-kushnir** [dasha-korotkykh/dariakorotkykh.com#24]
I mean, "6th of October, 1986" is probably grammatically correct, but it _could_ be hard to read, especially if  there's a ton of that on the page. Do we really want to be grammar nazi here? Even if we do — are we sure that " of " is _absolutely_ mandatory?

**Comment by oladushkas** [comment]
Totally agree. 
For the sake of saving reader's attention for really valid content ("what" and "where") I would have minified "when" to 6.10.1986; I believe that the exact date should be mentioned, but it could be done in a more laconic fashion. 
Not sure about that idea though, need your comment.

**Comment by volodymyr-kushnir** [comment]
"6.10.1986" would be perfect to memorize (obviously, because it's easier to memorize numbers than numbers _and_ letters), but nobody's really interested in memorizing all dates, so their primary task is to look good. "6.10.1986" is too "machine" and has "no heart".

**Comment by oladushkas** [comment]
Agreed, so be it:
6<sup>th</sup> October 1986

**Comment by telgerot** [comment]
This is my first contributing comment, yay me!

Okay so regarding dates:  there are a few writing conventions that are technically correct, but I think it's just a matter of taste:

If you want to write out everything and have the day first (unlike American savages), then it should be:
"(the) 6th of October, 1986"

I put "the" in parentheses because it's never actually **written**, only **spoken** that way.  Yeah, I know, it's weird.  If you wanted to the American (possibly British?) way, it would be month/day/year:

"October 6th, 1986" 

Note there is always a comma before the year.  Now, my _preferred_ method is military style:

"6 OCT 1986"

Really easy to read, no extra punctuation/article bullshit, just straight and to the point.  
But honestly it's not a big deal as long as people know what the damn date is, haha.
