### ISSUE TITLE
Don't link to Google Slides presentation for the talk on Happiness Management

### ISSUE THREAD

**Issue by dasha-korotkykh** [dasha-korotkykh/dariakorotkykh.com#47]
Remove it!

**Comment by volodymyr-kushnir** [comment]
I'm not sure if you need that link at all. I would probably either left it as is or removed the link altogether. If you keep it then you might want to add some sort of disclaimer to the resume (not slides themselves) and explain what reader should expect to see there. You don't have to modify the slides, that's for sure. That would be "semantically" incorrect. And I have my doubts about keeping that link because it doesn't say much except "I can put a bunch of GIFs in my slides and give an entertaining talk for 15 minutes". But there's a possibility that people would think that's the _only_ thing you can do. Hence, I would just remove the link and only mention that the talk did happened.

**Comment by dasha-korotkykh** [comment]
I did not mean putting the actual text over slides — never do that. However, in Google Slides there is a field text under each slide, where you can put down notes about it — one can use it to prepare for presentation or to make it self-explanatory. 
On the other hand, it is true that
> there's a possibility that people would think that's the only thing you can do
so thanks for the advise, probably that is not the piece I really want to broadcast.

**Comment by volodymyr-kushnir** [comment]
Hence, this task can be renamed to "Don't link to Google Slides presentation for the talk on Happiness Management" and an actual task would be to remove the link.
