### ISSUE TITLE
Restyle colour scheme to three-colour (also addresses #14)

### ISSUE THREAD

**Issue by dasha-korotkykh** [dasha-korotkykh/dariakorotkykh.com#50]
[Role model website](https://volodymyrkushnir.com/) employs just three main colours (with exception of highlights and emojis): black and shades of grey for text and midnight-blue for accents and links. 

Given the extension of my content, colourful tags are used to label corresponding activity types, but I would prefer to format the text to be more readable (add spaces between entries, really would love to steal that grey shade on current work entry, maybe think of something else). The goal is to make the resume less colourful, more consistent. I could also be deeply wrong about it in terms of UX, but didn't manage to find any actual info supporting or defying this intention.

**Comment by volodymyr-kushnir** [comment]
I would argue against it actually. I do agree on making the resume more consistent, hence, when you'll close #45, you'll loose colors and tags temporarily. We'll surely return them later, because I believe that the resume of "people's person" should be what, "playful"? This is why I would suggest to bring back the tags later and also add an option for different backgrounds. The latter would have to be designed and discussed separately, but I can drop you a hint — go see [**Google Fonts**](https://fonts.google.com/) and how they allow you to change the background using the control in top right corner.
